/* Auto-generated by tools/export_int8.py — do not edit manually */
#ifndef WEIGHTS_INT8_CRC_H
#define WEIGHTS_INT8_CRC_H

#define WEIGHTS_INT8_CRC32 0x606E1EC2U
#define WEIGHTS_INT8_SIZE  3169828U

#endif /* WEIGHTS_INT8_CRC_H */
