/* Auto-generated by tools/export_model.py — do not edit manually */
#ifndef WEIGHTS_CRC_H
#define WEIGHTS_CRC_H

#define WEIGHTS_CRC32 0x176A3D5AU
#define WEIGHTS_SIZE  12608056U

#endif /* WEIGHTS_CRC_H */
