/* Auto-generated by tools/calibrate_int8.py — do not edit manually */
#ifndef WEIGHTS_INT8_W8A8_CRC_H
#define WEIGHTS_INT8_W8A8_CRC_H

#define WEIGHTS_INT8_W8A8_CRC32 0x8EE45DEAU
#define WEIGHTS_INT8_W8A8_SIZE  3170332U

#endif /* WEIGHTS_INT8_W8A8_CRC_H */
