import struct
import numpy as np
import torch
import torch.nn as nn
import os
import zlib

def repack_for_neon(weight_np):
    C_out, C_in, K, _ = weight_np.shape
    C_out_pad = ((C_out + 3) // 4) * 4
    w = weight_np.reshape(C_out, C_in * K * K).astype('float32')
    if C_out_pad > C_out:
        w = np.concatenate([w, np.zeros((C_out_pad - C_out, C_in * K * K), dtype='float32')], axis=0)
    w = w.reshape(C_out_pad // 4, 4, C_in * K * K)
    w = w.transpose(0, 2, 1)
    return w.flatten()

def repack_for_neon_8ch(weight_np):
    C_out, C_in, K, _ = weight_np.shape
    C_out_pad = ((C_out + 7) // 8) * 8
    w = weight_np.reshape(C_out, C_in * K * K).astype('float32')
    if C_out_pad > C_out:
        w = np.concatenate([w, np.zeros((C_out_pad - C_out, C_in * K * K), dtype='float32')], axis=0)
    w = w.reshape(C_out_pad // 8, 8, C_in * K * K)
    w = w.transpose(0, 2, 1)  # [C_out/8, C_in*K*K, 8]
    return w.flatten()

def write_tensor(f, arr):
    flat = arr.astype(np.float32).flatten()
    f.write(struct.pack('<I', len(flat)))
    f.write(flat.tobytes())

def crc32_of_file(path):
    """Compute standard CRC32 (IEEE 802.3, same polynomial as crc32_sw in kernel.cpp)."""
    crc = 0
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            crc = zlib.crc32(chunk, crc)
    return crc & 0xFFFFFFFF

def write_weights_crc_header(weights_path, header_path):
    """Generate src/weights_crc.h with WEIGHTS_CRC32 and WEIGHTS_SIZE."""
    crc = crc32_of_file(weights_path)
    size = os.path.getsize(weights_path)
    with open(header_path, 'w') as f:
        f.write("/* Auto-generated by tools/export_model.py — do not edit manually */\n")
        f.write("#ifndef WEIGHTS_CRC_H\n")
        f.write("#define WEIGHTS_CRC_H\n\n")
        f.write(f"#define WEIGHTS_CRC32 0x{crc:08X}U\n")
        f.write(f"#define WEIGHTS_SIZE  {size}U\n\n")
        f.write("#endif /* WEIGHTS_CRC_H */\n")
    print(f"  weights_crc.h: CRC32=0x{crc:08X}, SIZE={size} bytes")

def main():
    print("=== Exporting YOLOv5n Weights (FP32 Optimized) ===")
    model = torch.hub.load('ultralytics/yolov5', 'yolov5n', pretrained=True)
    model.cpu()
    model.eval()

    src_dir = os.path.join(os.path.dirname(__file__), '..', 'src')
    weights_path = os.path.join(src_dir, 'weights.bin')

    with open(weights_path, 'wb') as f:
        print("Exportando capas...")
        for name, m in model.named_modules():
            if isinstance(m, nn.Conv2d):
                w = m.weight.detach().cpu().numpy()
                C_out, C_in, K_h, K_w = w.shape

                # 8-ch for K>1, C_out%8==0, C_out>=32; 4-ch for K>1, C_out%4==0; else flat
                if K_h > 1 and C_out % 8 == 0 and C_out >= 32:
                    write_tensor(f, repack_for_neon_8ch(w))
                elif K_h > 1 and C_out % 4 == 0:
                    write_tensor(f, repack_for_neon(w))
                else:
                    write_tensor(f, w)

                if m.bias is not None:
                    write_tensor(f, m.bias.detach().cpu().numpy())
                else:
                    write_tensor(f, np.zeros(w.shape[0], dtype=np.float32))

    print(f"\nDone. Exported to {weights_path}")

    # S8: compute CRC32 and write src/weights_crc.h for integrity check in kernel.cpp
    header_path = os.path.join(src_dir, 'weights_crc.h')
    write_weights_crc_header(weights_path, header_path)

if __name__ == "__main__":
    main()
