/* AUTO-GENERATED by tools/export_model.py — do not edit manually */
#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

/* Input */
#define INPUT_H     64
#define INPUT_W     64
#define INPUT_C     3

/* Layer 1: Conv2d(3->16, 3x3, s=1, p=1) + BN */
#define L1_IN_CH    3
#define L1_OUT_CH   16
#define L1_KER_SZ   3
#define L1_STRIDE   1
#define L1_PAD      1
#define L1_OUT_H    64
#define L1_OUT_W    64

/* Layer 2: Conv2d(16->32, 3x3, s=2, p=1) + BN */
#define L2_IN_CH    16
#define L2_OUT_CH   32
#define L2_KER_SZ   3
#define L2_STRIDE   2
#define L2_PAD      1
#define L2_OUT_H    32
#define L2_OUT_W    32

/* Layer 3: Conv2d(32->64, 3x3, s=2, p=1) + BN */
#define L3_IN_CH    32
#define L3_OUT_CH   64
#define L3_KER_SZ   3
#define L3_STRIDE   2
#define L3_PAD      1
#define L3_OUT_H    16
#define L3_OUT_W    16

/* MaxPool 2x2 s=2 */
#define POOL_OUT_H  8
#define POOL_OUT_W  8

/* YOLO head: Conv1x1(64->6) */
#define HEAD_IN_CH  64
#define HEAD_OUT_CH 6
#define GRID_H      8
#define GRID_W      8

/* Weight offsets (in floats from weights_start) */
#define W_CONV1_OFF  0
#define W_BN1_OFF    432
#define W_CONV2_OFF  464
#define W_BN2_OFF    5072
#define W_CONV3_OFF  5136
#define W_BN3_OFF    23568
#define W_HEAD_W_OFF 23696
#define W_HEAD_B_OFF 24080

#define TOTAL_WEIGHTS_SIZE 96344  /* bytes, unchanged */

#endif /* MODEL_CONFIG_H */
