/* File: src/ops.h — Bare-metal neural network operator library.
 *
 * All tensors use CHW (channel-first) layout:
 *   buf[channel][row][col] = buf[c*H*W + y*W + x]
 *
 * No standard library is required; this is safe for -ffreestanding -nostdlib.
 */
#ifndef OPS_H
#define OPS_H

#include <stdint.h>

/* ------------------------------------------------------------------
 * BatchNorm (inference, pre-fused affine)
 *
 * Applies per-channel scale and bias in-place.
 * buf layout: [C][HW]  (CHW format, contiguous per channel)
 *   buf[c*HW + i] = scale[c] * buf[c*HW + i] + bias[c]
 *
 * HW  = spatial size (H × W)
 * C   = number of channels
 * scale/bias = pre-fused from export_model.py:
 *   scale[c] = gamma[c] / sqrt(var[c] + eps)
 *   bias[c]  = beta[c] - mean[c] * scale[c]
 * ------------------------------------------------------------------ */
void batchnorm_inplace(float* buf, int HW, int C,
                       const float* scale, const float* bias);

/* ------------------------------------------------------------------
 * LeakyReLU (in-place)
 *   y = x > 0 ? x : 0.1 * x
 * ------------------------------------------------------------------ */
void leaky_relu_inplace(float* buf, int n);

/* ------------------------------------------------------------------
 * MaxPool 2×2, stride 2 (CHW format)
 *   in  : [C][H][W]
 *   out : [C][H/2][W/2]
 * ------------------------------------------------------------------ */
void maxpool2x2(const float* in, float* out, int H, int W, int C);

/* ------------------------------------------------------------------
 * Generic Conv2d — scalar reference (correctness / fallback)
 *   in  : [C_in][H_in][W_in]
 *   w   : [C_out][C_in][K][K]   (PyTorch standard layout)
 *   out : [C_out][H_out][W_out]
 * ------------------------------------------------------------------ */
void conv2d_cpp(const float* in, int H_in, int W_in, int C_in,
                const float* w, int C_out, int K, int stride, int pad,
                float* out);

/* ------------------------------------------------------------------
 * NEON Conv2d — 4 output channels per NEON vector  (FAST PATH)
 *
 * w_rep : NEON-repacked weights [C_out/4][C_in*K*K][4]
 *         (generated by tools/export_model.py::repack_for_neon)
 *
 * C_out must be divisible by 4.
 * Uses vld1q_f32 + vmlaq_n_f32 in the inner loop.
 * ------------------------------------------------------------------ */
void conv2d_neon_4ch(const float* in, int H_in, int W_in, int C_in,
                     const float* w_rep, int C_out, int K,
                     int stride, int pad, float* out);

/* ------------------------------------------------------------------
 * Conv 1×1 with bias (YOLO head)
 *   in  : [C_in][H][W]
 *   w   : [C_out][C_in]   (1×1 kernel, flattened)
 *   b   : [C_out]
 *   out : [C_out][H][W]
 * ------------------------------------------------------------------ */
void conv1x1(const float* in, int H, int W, int C_in,
             const float* w, const float* b, int C_out,
             float* out);

/* ------------------------------------------------------------------
 * YOLO decode
 *
 * head_out: [6][grid_H][grid_W]  in CHW format
 *   channel 0: tx  (sigmoid → x offset within cell)
 *   channel 1: ty  (sigmoid → y offset within cell)
 *   channel 2: tw  (exp     → width  relative to anchor)
 *   channel 3: th  (exp     → height relative to anchor)
 *   channel 4: obj_conf  (sigmoid)
 *   channel 5: cls_conf  (sigmoid, single class)
 *
 * Anchor size: 1.0 × 1.0 (normalized to grid)
 * obj_thresh: minimum confidence to emit a box
 *
 * Returns number of boxes written.
 * ------------------------------------------------------------------ */
struct BBox {
    float x, y, w, h;  /* centre-x, centre-y, width, height (normalised 0..1) */
    float conf;         /* objectness * class confidence */
    float cls;          /* raw class confidence */
};

int yolo_decode(const float* head_out, int grid_H, int grid_W,
                float obj_thresh, BBox* boxes, int max_boxes);

#endif /* OPS_H */
