/* src/safety_config.h — Named constants + safety macros (ISO 26262 ASIL-B)
 *
 * Central header for thresholds, geometry, and safety primitives.
 * All files using SAFETY_ASSERT / SAFETY_HALT must have uart_puts visible.
 */
#ifndef SAFETY_CONFIG_H
#define SAFETY_CONFIG_H

/* === Inference Thresholds === */
#define CONF_THRESH        0.5f
#define NMS_THRESH         0.35f
#define OBJ_PRE_THRESH     0.45f   /* objectness pre-filter in decode_yolo_grid */

/* === Model Geometry === */
#define NUM_CLASSES        80
#define MAX_PREDS          100
#define NUM_ANCHORS        3

/* === Safety Constants === */
#define STACK_CANARY_MAGIC 0xDEADBEEFDEADBEEFULL
#define DISPATCH_TIMEOUT   50000000UL   /* ~50M cycles (~50ms @ 1GHz) */

/* === Weights integrity (auto-generated by tools/export_model.py) === */
#ifdef __has_include
#  if __has_include("weights_crc.h")
#    include "weights_crc.h"
#  endif
#endif
#ifndef WEIGHTS_CRC32
#define WEIGHTS_CRC32 0x00000000U   /* fallback: 0 = skip check; run export_model.py */
#endif

/* === Safety Macros ===
 * Require uart_puts() to be visible in the including translation unit. */
#define SAFETY_ASSERT(cond, msg) \
    do { if (!(cond)) { uart_puts("[SAFETY] "); uart_puts(msg); uart_puts("\r\n"); while(1); } } while(0)

#define SAFETY_HALT(msg) \
    do { uart_puts("[HALT] "); uart_puts(msg); uart_puts("\r\n"); while(1); } while(0)

#endif /* SAFETY_CONFIG_H */
