/* Auto-generated by tools/export_model.py — do not edit manually */
#ifndef WEIGHTS_CRC_H
#define WEIGHTS_CRC_H

#define WEIGHTS_CRC32 0xC8C55F60U
#define WEIGHTS_SIZE  7470100U

#endif /* WEIGHTS_CRC_H */
